spring:
  application:
    name: bloom-filter-study
  datasource:
    url: jdbc:mysql://localhost:3306/bloom_filter?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost # Redis?????
      port: 6379 # Redis?????
      password:
      timeout: 6000ms # ??????
      database: 2

server:
  port: 8124
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    # MyBatis ??
    map-underscore-to-camel-case: false
    # ??????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl